### ISSUE TITLE
Avoid random segfaults

### ISSUE THREAD

**Issue by Yajo** [Tecnativa/docker-odoo-base#10]
Seems like some of Odoo dependencies needs glibc, possibly Pillow: https://github.com/python-pillow/Pillow/issues/1935.

To reproduce, just run the scaffolding for v10, install `account_accountant` addon, and go to *Account* menu. **Odoo simply dies with exit code 139**. No exceptions, no traceback, just dies.

According to above issue, it seems like possibly Pillow or some of its dependencies (or Odoo's) [needs something that it only can get from glibc, and is thus incompatible with musl](http://wiki.musl-libc.org/wiki/Functional_differences_from_glibc).

We could try to use [a glibc-enabled Alpine](https://hub.docker.com/r/frolvlad/alpine-glibc/), but that [does not seem too much stable and secure for production](https://github.com/gliderlabs/docker-alpine/issues/11#issuecomment-237842562). I think for this case we will sadly need to use another distro. Let's try with debian.

**Comment by pedrobaeza** [comment]
I understand the only drawback is the size of the image, isn't it?

**Comment by pedrobaeza** [comment]
Isn't pillow recompilable from source against musl libc?

**Comment by Yajo** [comment]
Indeed, image will grow by ~600MB.

 Pillow is now installed by compiling against musl, and nothing seems to be wrong at compile time seems to be a heisenbug (I reproduce it unless I debug step by step 😆), thus hard to close upstream.

I still can try to change the LDFLAGS before completely dropping Alpine.

**Comment by pedrobaeza** [comment]
OK, storage is cheaper than your time mostly, so let's try a bit more, and if not, we can switch.

**Comment by lasley** [comment]
Damn yeah this is confirmed on our image too, which we have yet to convert over to this one.

Curious, did you try the glibc version of Alpine just to see if this is in fact the issue?

**Comment by lasley** [comment]
My impatience got the best of me, this does work on the glibc Alpine. That sucks..

**Comment by pedrobaeza** [comment]
But that base is not very stable as @Yajo commented, isn't it? Our investigation line has been to get all correctly compiled against murl, but @Yajo is only in the morning, so this goes slower.

**Comment by lasley** [comment]
Definitely not a good idea for production, but also cuts out a variable that existed otherwise. We now know that this is definitely an issue with compilation, as @Yajo abstracted. Really this is more of a hypothesis confirmation than anything - At least we know we're barking up the wrong tree and all that.

**Comment by Yajo** [comment]
Yeah, I'd love to get this alpine-based, but my compilations knowledge goes not too far from following the steps found in project's install instructions. I'm afraid I'm not capable right now to fix that in Pillow, and using this derivated version with mixed glibc & musl feels a little bit unstable for production.

It's absurd that you can have linux kernel, postgres, haproxy, and almost all Odoo working fine with musl, and this Pillow library not. But that's the case and after all, the purpose here is "follow readme, turn on, all works". If Alpine right now does not allow that, then the fastest solution on our side is to switch to Debian. I'm going to tag the last Alpine commit in history, so that if you get to fix it in Pillow, we can go back to that point.

At least I'm going to use the `debian:8` image instead of the `python:2` one. The python one is too full of build garbage that we don't need. My hope is that this will get only ~100 extra MB.

**Comment by Yajo** [comment]
![It's alive! 🎉](https://cloud.githubusercontent.com/assets/973709/21680175/4f8448e4-d348-11e6-989a-dc479527b1c5.jpg)

Finally fixed in https://github.com/Tecnativa/docker-odoo-base/commit/1b4fe55a43bf57f91d441053deb7a7f133229a35, now we have it working under Debian, and just with ~70 extra MB.

**Comment by Yajo** [comment]
BTW, there's [the `alpine` tag](https://github.com/Tecnativa/docker-odoo-base/releases/tag/alpine) as a record to roll back to it if @lasley makes Pillow work in musl 😊

**Comment by lasley** [comment]
I'm pretty determined to get it working, so I think we'll crack this nut eventually. My random compile option dartboard experiment yesterday obviously failed, so now I'm working on generating an isolated test case that doesn't need Odoo. It's definitely in side time though, so progress might be slow.

**Comment by Yajo** [comment]
Great news 😊 

The cool thing is that the only "breaking" part by moving from Alpine to Debian was to change `#!/bin/sh` for `#!/bin/bash` in subimage scripts, if any. So when you fix and we go back to Alpine, we will just have to change that back again and all *should* work.

**Comment by lasley** [comment]
Hooray!

Curious - why did Debian not work when using `sh`? This is my go-to shell when building scripts because I was under the impression it was the one I could guarantee would be in all things *Nix 😖

**Comment by Yajo** [comment]
Not sure, seems like it was raising syntax errors with `[` in `if`s.

BTW, after https://github.com/python-pillow/Pillow/issues/1935#issuecomment-277064005, do you have any clues of the real problem? Did you open anything against `lxml`?

**Comment by lasley** [comment]
Still working on that. I don't want to open the issue without a test case for fear of bugging someone so l33t again. My debugging skills just had circles run around them, I don't want that to happen twice!

**Comment by wiredfool** [comment]
Looks like it might just be a stack size issue: https://github.com/python-pillow/Pillow/issues/1935#issuecomment-277648059
