### ISSUE TITLE
Use a better fakesmtp

### ISSUE THREAD

**Issue by Yajo** [Tecnativa/docker-odoo-base#101]
Current fakesmtp just logs "a mail has been sent". Not very useful for development.

https://github.com/mailhog/MailHog seems to be a better default for that purpose. Maybe there are others? They have an official docker image; it should be easy to plug in the scaffolding.

**Comment by njeudy** [comment]
First initiale version un merge request .. 
I think we can do better with configure real external SMTP and using mailhog in production launching phase to trap all smtp message, and if they are ok, release it to real smtp server .. 

It can be done when changing mail template, or testing new modules to avoid customer to receive wrong email :)

**Comment by Yajo** [comment]
Fixed in #107.

To use mailhog in production please open a new issue/PR. Thanks!
