### ISSUE TITLE
traefik let's encrypt  tls-sni-01 issue

### ISSUE THREAD

**Issue by DarioLodeiros** [Tecnativa/docker-odoo-base#116]
I'm having problems with Let's encrypt certificate, I think that its related with [https://github.com/containous/traefik/pull/2701](https://github.com/containous/traefik/pull/2701)
Can you confirm this issue with tls-sni-01? or, on the contrary, does the generation of the certificate work correctly?
Thanks!

**Comment by lasley** [comment]
Hi @DarioLodeiros - what is the specific problem you are encountering, and what leads you to believe it is due to an asset provided here?

**Comment by DarioLodeiros** [comment]
Hi!This is tue specific issue in traefik log:https://github.com/containous/traefik/issues/2691acme: Could not determine solvers www.domain.com:[www.domain.com] acme: Could not determine solvers]" I try with 4 servers and 4 different domains. One week ago, it work fine.... But since some days ago, I always get this issue.Thanks!El 17 ene. 2018 11:23 p. m., Dave Lasley <notifications@github.com> escribió:Hi @DarioLodeiros - what is the specific problem you are encountering, and

**Comment by pedrobaeza** [comment]
LE has disabled the method Traefik gets certificates, so yes, it's affecting. There's a new beta version for using another method. My colleague @Yajo can give you more details.

**Comment by pedrobaeza** [comment]
The reason after the disabling is a vulnerability found.

**Comment by DarioLodeiros** [comment]
Thanks!
:)

**Comment by Yajo** [comment]
Just use the `traefik:1.5` image for the time being. It's still RC, but works.

**Comment by DarioLodeiros** [comment]
Ok! I tried 1.5-Alpine with the same result, but I will try 1.5
Thanks!!

**Comment by pedrobaeza** [comment]
If you have reached limit for requests, you will have to wait until the rate is restored.

**Comment by DarioLodeiros** [comment]
I have tried changing the version traefik image in inverse_proxy yaml, the 1.3-alpine by 1.5, with a new domain, in a new server.... but the same result... acme: Could not determine solvers 
I'm missing something?

thanks!!

**Comment by lasley** [comment]
I would just use DNS challenge in the interim - https://serverfault.com/questions/750902/how-to-use-lets-encrypt-dns-challenge-validation

**Comment by Yajo** [comment]
The fix: https://github.com/containous/traefik/issues/1832#issuecomment-359546437

I'll update the docs
