### ISSUE TITLE
AUTO_REQUIREMENTS should ignore Odoo's "requirement.txt"

### ISSUE THREAD

**Issue by crimoniv** [Tecnativa/docker-odoo-base#125]
_(Tested in Odoo 8.0 but other versions may also be affected)_

With the change introduced in https://github.com/Tecnativa/docker-odoo-base/commit/02aa051c1cc473cf17bbf4d13fc54d082f15965f#diff-68166c6ea12c779a6137a456d7da2429L23, `AUTO_REQUIREMENTS=true` fails to install `odoo/requirements.txt`.

As this file is already installed by https://github.com/Tecnativa/docker-odoo-base/blob/master/bin/install.sh, should that change be reverted to check only module directories?

**Comment by Yajo** [comment]
Nope, sorry, that's on purpose. In case those requirements already exist, pip will ignore them; but in case your Odoo fork specifies new requirements, they should be honored, and that's why we don't ignore that file.

**Comment by crimoniv** [comment]
Oh I see, it is fetching the `requirements.txt` from `ODOO_SOURCE=OCA/OCB` in the base image, thank you for pointing it out.

So I think the best option is to have this file synced in any Odoo fork –instead of building the base image with a custom `ODOO_SOURCE`–. Maybe it is worth mentioning that behaviour in the `README.md` to avoid any misunderstanding.

**Comment by Yajo** [comment]
Don't worry, you can use whatever Odoo fork you want. It's just gonna be faster if you use OCB because it's the recommended one.
