### ISSUE TITLE
Issue to import a new database backup from odoo interface

### ISSUE THREAD

**Issue by DarioLodeiros** [Tecnativa/docker-odoo-base#129]
When I try import a odoo backup form web/database/manager, I get a error to drop the default database (database 'devel/prod/test' not exist)... I remmeber that before this ran ok, but now... I dont know If is a issue or exist other way...
Thanks!

**Comment by DarioLodeiros** [comment]
I think that this issue only happens with 11.0 version. When I delete the database, to restore other backup, the system dont allow access to database manager, Internal Server:
This is the log:
![seleccion_039](https://user-images.githubusercontent.com/11718836/37567854-38359e30-2acd-11e8-8210-1d1473094fc9.png)
I need restore the database by psql and rename it to sucess...

**Comment by pedrobaeza** [comment]
But this is normal, as the database doesn't exists. What you have to do is:

1. Launch instance.
2. Go to database manager.
3. Remove `devel` DB that has been created automatically.
4. Restore backup.

**Comment by DarioLodeiros** [comment]
Yes... the problem is thtat after the 3 point, I get this error, and I cant access to database manager to restorer de backup.

**Comment by pedrobaeza** [comment]
Strange, but anyway, we are not using this manual method of doing things. Have you seen our duplicity backup and restore system?

**Comment by DarioLodeiros** [comment]
Yes, I know. But... are you using this method in devel env? When you
want download a customer bbdd are you using de S3 bbdd?, Ok, It's a
possible solution, anyway, Its strange that in < v11 the
database/manager load ok without database, and yet, in v11 image, Its
give a database error when trying to enter in database/manager. 

Thanks for your efforts! 

---

El 19.03.2018 09:43 AM, Pedro M. Baeza escribió: 

> Strange, but anyway, we are not using this manual method of doing things. Have you seen our duplicity backup and restore system? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/Tecnativa/docker-odoo-base/issues/129#issuecomment-374138073
[2]

**Comment by pedrobaeza** [comment]
Well, first, I don't usually dump any customer DB in my local environment, because if you need to do that, something in your pipeline is not correct (unit tests, demo data, CIs...), and you should be very careful about LOPD and GDPR doing this, but the short answer is yes, for that weird occasion, we use S3 for recovering the DB.

**Comment by DarioLodeiros** [comment]
Yes, it's certainly not a common procedure... although eventually you may be forced to do so. Anyway I dont want to divert the focus... If someone know this issue, or know that it works for him... I appreciate your feedback!
Thanks a lot!

**Comment by Yajo** [comment]
This is Odoo's bug, please report it there. Thanks!
