### ISSUE TITLE
Why not make the proxy part of the image?

### ISSUE THREAD

**Issue by sylnsr** [Tecnativa/docker-odoo-base#135]
So you are using Traefik in another container and proxy through it to the Odoo container. While this follows the typical one-container-one-function paradigm .. it's not totally without precedent to have something like Traefik running in the same container as Odoo, and letting [tini](https://github.com/krallin/tini) get PID 1.

One might argue that the Odoo container should only have the Odoo process and not have its environment cluttered with another process but in reality, even Odoo will spin up other processes when you increase workers in the config.

So why do this?

  For one thing, it keeps deployment simpler since you just spin up one container.
  Removes the single point of failure: If the reverse proxy container goes down, all nodes behind it are useless.
  Is more scalable: As you add more Odoo nodes, your reverse proxy node could eventually be saturated. Having a reverse proxy in the Odoo container means that as I scale up the number of containers, I am also scaling up the number of reverse proxies in parallel.

[I have been using this paradigm](https://github.com/idazco/odoo-docker-ez) in production for almost a year and have been very pleased with the results.  Traefik looks enticing though and I might switch to using that instead of nginx.

Thoughts?

**Comment by sylnsr** [comment]
@crazy-projects, my use is the same as yours .. SSL termination is at the AWS ELB level. I think this is actually the typical case, so nginx .. or whatever reverse proxy is used ... is just for the sake of getting things working  in Odoo that require it, and should not do more than that.  There are things that are specialized for SSL termination (and security) in production environments so its best to use those things.

Along those lines .. the thing I do different is I use AWS WAF to prevent access to certain URLs, such as the dbmanager. This is just more load I can take off the containers by having this delegated to WAF instead of the reverse proxy inside the container.  If you check your traffic carefully you might see, as I did, a lot of bot and scanner requests coming in  (especially from [jorgee](https://www.google.com/search?q=user-agent+jorgee), [zmeu](https://www.google.com/search?q=user-agent+zmeu) and [yunjiankong](https://www.google.com/search?q=user-agent+yunjiankong)) -- in some cases this exceeded legitimate Odoo traffic, so handling this with the reverse proxy in the same container as Odoo is not ideal.

**Comment by Yajo** [comment]
Hi everyone.

It's best to have 1 app per container, always.

The only benefit of doing the other way around would be when you want to boot a production-ready Odoo and bind it to port 80 & 443 directly, but if you need more than 1 Odoo container running together into the same machine or swarm (no matter if they are 2 servers for the same database, or 2 completely different projects), you always need an inverse proxy to balance traffic among them in some unknown and possibly unstandard ways.

The fact of the inverse proxy being your SPF here is not true. It just one of the failure points you have. You could lose network, your database server could stop, an exception while updating an addon could render Odoo unbootable, or your ISP could be burned by a nuclear weapon.

There are strategies to mitigate each of those scenarios, but it's best that deployers investigate those and apply them at their bests. For your comments I can see that most of you are using nginx. We recommend and pseudo-support Traefik, but thanks to not applying what you ask us to do here, you can use the inverse proxy of your preference.

This image is focused on Odoo, and that's how it will continue to be. This standpoint also simplifies support on our side.

Thanks for your understanding.

**Comment by pedrobaeza** [comment]
Completing @Yajo's comment, we have our full stack for Odoo deployment developed, but that's as a Docker compose project which separates each service per container. See the branch https://github.com/Tecnativa/docker-odoo-base/tree/scaffolding for the scaffolding, and other Tecnativa/docker-* projects for the rest of containers.

**Comment by sylnsr** [comment]
Regarding .."The fact of the inverse proxy being your SPF here is not true ...You could lose network, your database server could stop".

True in _your_ case, apparently.  If you don't have redundancy for those things as well, as I do, then you're obviously operating at an entirely different level. I actually _do_ run my instances as if my AWS datacenter could be nuked, which is why I have multi AZ deployments for _everything_ and redundancy for _everything_ so if I was to use the setup from this project Traefik _would_ be the SPF. To me there is never a question of "**if** you need more than 1 Odoo container" .. I _always_ run multiple load balanced instances in-case one goes down. In a production environment, how is this even an option?

All that is fine. I guess the underpinning point here, is that the philosophy of this project is incompatible with someone wanting to run a nuke proof setup, which is what I was seeking to find out.

**Comment by Yajo** [comment]
This thread just hit my daily absurdity limits, blocking.

**Comment by pedrobaeza** [comment]
@sylnsr I think you are very wrong on all your statements and probably our project is far more solid rock, or at least we are more skilled in Docker topics, but hey, do what you want. We don't want people with your attitude in this community.
