### ISSUE TITLE
[11.0] New interaction between  --database and --db-filer parameters

### ISSUE THREAD

**Issue by lreficent** [Tecnativa/docker-odoo-base#137]
From Odoo documeantation: https://www.odoo.com/documentation/11.0/reference/cmdline.html
> Since version 11, it's also possible to restrict access to a given database listen by using the --database parameter and specifying a comma-separated list of databases
When combining the two parameters, db-filter superseed the comma-separated database list for 
restricting database list, while the comma-separated list is used for performing requested operations like upgrade of modules.

This is causing an issue on the database manager when running odoo using this image: only the devel, test or prod databases are going to be displayed (depending on the stage you are). This is specially inconvinient on the devel stage where we may duplicate or create new databases often.

**Comment by Yajo** [comment]
Indeed, we need to supply a default db_filter that is `.*`, which would make it work under any Odoo version.

We'll need to warn in #67, just in case somebody already has a db-filter configured and it could potentially break it.

**Comment by lreficent** [comment]
That sound good to me! Would you do it or do you want me to open a PR?

**Comment by lreficent** [comment]
Fixes merged
