### ISSUE TITLE
Go back to Alpine

### ISSUE THREAD

**Issue by Yajo** [Tecnativa/docker-odoo-base#16]
This is a placeholder to track all progress on why we went away from Alpine base and how we could get back.

# Why do we want it back?

- Base Debian image is ~123MB, base Alpine one is ~4MB. (TODO: Is it worth it? After all Odoo has such a big amount of dependencies...)
- `apk` (Alpine package manager) allows virtual packages, which make the Dockerfile much more straightforward.

# Why did we leave it?

- We were getting random segfaults (well, not so random, [you can reproduce them](https://github.com/python-pillow/Pillow/issues/1935#issuecomment-276905234)).

# Where did we leave it?

Right now, [there's the `alpine` tag](https://github.com/Tecnativa/docker-odoo-base/releases/tag/alpine), that holds the last commit that was Alpine-based.

# Workarounds available

- ~~[Increasing threading stack size](https://github.com/python-pillow/Pillow/issues/1935#issuecomment-278134137).~~ Reported [not working 100% fine](https://github.com/Tecnativa/docker-odoo-base/pull/15#issuecomment-280857104).

# Who's the culprit?

Some C library, possibly.

- Pillow? [Possibly not](https://github.com/python-pillow/Pillow/issues/1935#issuecomment-277648059).
- [lxml?](https://github.com/Tecnativa/docker-odoo-base/pull/15#issuecomment-280857104)

**Comment by Yajo** [comment]
Note to self: in odoo 11, with python 3, maybe this can help debugging the problem: https://docs.python.org/3/whatsnew/3.3.html#faulthandler

**Comment by iNaKoll** [comment]
faulthandler is also available for python 2: 
https://pypi.python.org/pypi/faulthandler/ :+1:

**Comment by Yajo** [comment]
Thanks!

Although thinking well on it, this project is too big now to do such breaking change just to save some 45MB of disk, so this will most likely never be fixed.

Sad, I wanted it on Alpine since the first day, but those hard to debug problems do not pay for just some disk space.
