### ISSUE TITLE
Maintain single branch

### ISSUE THREAD

**Issue by Yajo** [Tecnativa/docker-odoo-base#2]
As stated by @lasley in https://github.com/Tecnativa/docker-odoo-base/issues/1#issuecomment-270717480, we should have only one branch with conditional install scripts depending on the Odoo version being installed.

**Comment by lasley** [comment]
Huzzaah! 

PS. I'm just using a lot of your code in my Docker at the moment, but will begin converting soon. Found a bug or two that I'll submit upstream too as I finish testing 😄

**Comment by Yajo** [comment]
Closed in 90b21f4fec66405a2c6f2d4fdaf5c8fc8dada88f (it did not close #1, but prepared it to be in the master branch). BTW I'm using now docker hub as a testing CI.

**Comment by lasley** [comment]
Is Dockerhub able to add statuses into PRs?

**Comment by Yajo** [comment]
i'm afraid not, that's the use case that would justify another CI indeed.

**Comment by lasley** [comment]
Yeah tags were the only idea I could come up with too. Oh well, I'll keep working on the docker-quality-tools then, but make it more compatible with the existing hub tests instead of the duct-tape stuff going on now.
