### ISSUE TITLE
Dependencies for Pillow (Debian stretch)

### ISSUE THREAD

**Issue by jbeficent** [Tecnativa/docker-odoo-base#22]
I was having trouble installing Pillow using buildout. FYI, here I found libs that are required:
https://github.com/python-pillow/docker-images/blob/master/debian-stretch-x86/Dockerfile

apt-get -y \
    install xvfb sudo \
    git wget python-numpy python-scipy netpbm \
    python-qt4 ghostscript libffi-dev libjpeg-turbo-progs \
    python-setuptools python-virtualenv \
    python-dev python3-dev cmake \
    libtiff5-dev libjpeg62-turbo-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev \
    python-tk python3-tk

**Comment by Yajo** [comment]
Sorry I don't understand the issue. Pillow is preinstalled in the image, what's your problem?

**Comment by jbeficent** [comment]
Just pointing out, that in case that you plan to upgrade to Debian Stretch, there were issues with Pillow.

**Comment by Yajo** [comment]
Oh thanks, once it hits stable we'll update. I'll keep this open until then.
