### ISSUE TITLE
SSH Keys for Private Repos

### ISSUE THREAD

**Issue by lasley** [Tecnativa/docker-odoo-base#30]
I am unable to get private repo SSH keys to work while building a scaffold. I've tried a lot of things, but the below is the most simple that definitely should have worked (it's in a `build.d` file):
```bash
#!/bin/bash
mkdir -p ~/.ssh
echo "RSA PRIVATE KEY" > ~/.ssh/id_rsa
echo "Host repo.laslabs.com
  IdentityFile ~/.ssh/id_rsa" > ~/.ssh/config
chmod 700 ~/.ssh/id_rsa
```

My guess here is that we aren't operating within a true shell, so the SSH config & key simply isn't being looked at. 

I've also tried to add this logic in my scaffold Dockerfile, but that's a bust because it's run after the repos are gathered.

Are you guys using any private repos at this point?

**Comment by pedrobaeza** [comment]
Create a file with +x in odoo/custom/build/ with this content:
```
set -e
private='
-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
'
public='
ssh-rsa ...== root@odoo
'

homes="/root /opt/odoo"
for dir in $homes; do
    dir=$dir/.ssh
    mkdir -p $dir
    echo "$private" > $dir/id_rsa
    echo "$public" > $dir/id_rsa.pub
    ssh-keyscan <git_host> >>$dir/known_hosts
    chmod -R u=rwX,go= $dir
    log INFO Added deployment keys to $dir
done
```
replace <git_host> with the name of your GIT private repos host and put the private and public keys. 

Then, you'll be able to add to repos.yaml and addons.yaml this private repo and addons.

**Comment by Yajo** [comment]
Maybe it would be good to bundle support for this, given it is a common use: have a `id_rsa` and `id_rsa.pub` files/args, and a `GIT_HOSTS` build arg and add this bunch of code in a bundled build script...

**Comment by lasley** [comment]
Thanks @pedrobaeza - exactly what I needed.

@Yajo - Yes, I am planning on submitting a PR to bundle support for this - your plan sounds solid too. This is totally common, and wasn't obvious enough IMO. I admittedly spent an hour or two before I gave up and submitted a ticket - I can only imagine how long that would have been for someone less experienced, or without a pre-existing relationship with the module maintainers.

**Comment by lasley** [comment]
Reporting back - Pedro's script seems to have the same issue as mine - the private key isn't actually being used for the gitaggregate clones. 

I checked, and gitaggregate works fine locally with the same key. The clone also works directly in the container, under the root and odoo users 😑 

Is this maybe something between the difference of a `bashrc` and `bash_profile`?

**Comment by Yajo** [comment]
It should work, we use it.
Have you checked https://github.com/Tecnativa/docker-odoo-base#why-my-99-whateversh-script-in-optodood-does-not-execute?
Also, did you remember to `docker-compose build --pull` after adding the script?

**Comment by lasley** [comment]
The script is executing - I see the log output for the deployment keys being added. 

Turns out that I forgot to add a `-p` in the ssh-keyscan to point to git instead of the system SSH. After fixing that, the clone worked great.

One issue I noticed though is that the ssh stuff in `/opt/odoo` is useless because it is owned by root. Adding the following to the bottom of the script was my solution:

```
chown -R odoo /opt/odoo
```

Although does the Odoo user really need access to the repos? Looks like everything is being done under root, unless I'm mistaken.

**Comment by Yajo** [comment]
Actually your points leaded me to discover a little security hole that will make your apt script possibly not work, maybe you will need to change a little thing: odoo's $HOME is now /home/odoo. See https://github.com/Tecnativa/docker-odoo-base/commit/1080ced6fe9fc1cb17f6942071a92de0afb59483 for details.
