### ISSUE TITLE
Commits on Master

### ISSUE THREAD

**Issue by lasley** [Tecnativa/docker-odoo-base#36]
Hey @Yajo - Now that I'm starting to use this repo, I'm having a lot of trouble following what's happening due to commits directly on master. Can I ask for a PR process? I don't really care if they're reviewed or anything (although I offer a hand in that), but my workflow revolves pretty heavily around monitoring PRs and not actual commits.

**Comment by pedrobaeza** [comment]
AFAIK they have been your PRs reworked in some way.

**Comment by lasley** [comment]
An example would be this https://github.com/Tecnativa/docker-odoo-base/commit/3256bc955b50cf277142dd76e633bdca7fcb96e1, where I would have argued before it went on master.

**Comment by lasley** [comment]
I'm assuming the real issue here is lack of CI, right? I'm having a damned old time testing independent branches, so I'm assuming you are too?

**Comment by pedrobaeza** [comment]
You're right. Till now, @Yajo has been the lonely rider here. Now that this is more crowded, better to follow PR convention.

And yes, the problem is the lack of proper testing via CIs, which is not easy in this case.

**Comment by lasley** [comment]
We're moving to begin rolling these images out to our prod instances starting Friday, so you can consider me around here for good at this point. I'll keep an eye out and review PRs, and will try to get #29 done for us today.

**Comment by pedrobaeza** [comment]
Cool, sorry for the inconveniences.

**Comment by lasley** [comment]
No inconvenience - you guys saved me so much work overall 😄 

I'll close this, there's no action items
