### ISSUE TITLE
[RFC] Move config generation to entrypoint

### ISSUE THREAD

**Issue by lasley** [Tecnativa/docker-odoo-base#37]
I wanted to open a discussion to move the Odoo configuration generation from the build into the entrypoint. I am mainly wondering what were the design considerations that led you to put it in the build?

My reasoning for entrypoint is as follows:
* Passwords are currently hard coded into the build image
  * Security issue - passwords should not be stored in the container registry (note that [ECR is not a HIPAA compliant service](https://aws.amazon.com/compliance/hipaa-eligible-services-reference/))
  * Maintenance issue - our policies require that all passwords are rotated on a consistent basis. This is much more difficult at the image level
  * Passwords stored in repo unencrypted (unless I'm missing something)
* Exponential image duplication - It is possible to have multiple customers on the same image if the config is generated on the fly
  * This is particularly important in my SaaS, where all images are identical except for the credentials.

Ummm that's all I can think of at the moment. Any thoughts?

**Comment by pedrobaeza** [comment]
I don't see special problem right now, although I'm not an specialist on Docker, but how do you plan to give passwords then?

@Yajo only works on mornings, so you won't receive his answer till tomorrow.

**Comment by lasley** [comment]
> but how do you plan to give passwords then?

Environment variables. This is the same strategy used by the Postgres container, which takes `POSTGRES_PASSWORD` + `POSTGRES_USER` env vars & creates the role based upon them on initial launch. 

In our case, I think we'd be safe generating the config on the fly every time as opposed to the init that the Postgres one does. The Postgres init is fairly high overhead, vs we're just text editing.

Taking it a step further, we have another repo for our customer deploys. This repo consists of folders for the customers, subfolders for their instances. In the subfolders are two files:
* `docker-compose.yml.vault`
* `rancher-compose.yml` 

These files describe the specifics of the instance deploy, with the `docker-compose` file being encrypted with Ansible vault. Our Ansible deployer unvault-ifies it & triggers the Rancher deploy.

> @Yajo only works on mornings, so you won't receive his answer till tomorrow.

No worries - Admittedly I had already kind of figured out his schedule at this point. Lucky duder - wish I worked only mornings!

**Comment by lasley** [comment]
It should also be noted that we're maintaining different vault passwords for each customer subfolder. I'd be happy to discuss that one in person, but it's a bit in depth & I'm not sure how public I want it just yet - for all I know, there's a gaping security hole 😉

**Comment by pedrobaeza** [comment]
Yes, there are several aspects still to be covered, hehe. OK, let's wait for the @Yajo's confirmation tomorrow, although I think you can start drafting the changes.

**Comment by lasley** [comment]
The modern wheel wasn't invented in a day!

One major thing to note - this change will require that all of your builds are updated to move the Odoo config items from the `args` section into the `environment`. That could be a major blocker depending on how many images you have, although I think it would be something that could be done with automation maybe.

**Comment by pedrobaeza** [comment]
Not really, as they are spread in the customer repos, but the improvements you mention are worth I think.
