### ISSUE TITLE
Question on License

### ISSUE THREAD

**Issue by lasley** [Tecnativa/docker-odoo-base#4]
Any thoughts on licensing this under MIT or BSD? I'd prefer to not have any of my infrastructure under (*)GPL if at all possible, even if it is hosting an LGPL app.

Note: the Python base & Postgres sidekick are MIT

**Comment by pedrobaeza** [comment]
What are the advantages of that licenses?

**Comment by lasley** [comment]
Really it all boils down to permissions for use. Client level applications license well under (*)GPL, but libraries and development headers are better under a more permissive license. 

This base is meant to be under many layers of other systems, all of which would need to be licensed under LGPL if the base is licensed as such. Same with any modifications that someone makes to the base (think the scaffolds - which could even contain my passwords). 

Comparing this against MIT or BSD though, modifications can be freely made and distributed other under licenses. New systems can be directly linked without enforcing terms on them as well.

Sure, this all seems like crap from the perspective of having just designed a piece of software that you people to continue to share. 

The tradeoff to this is a matter of system adoption. A perfect example is the fact that I will not be able to use this in my infrastructure & will have to design a competing system - fracturing our basically non-existent Odoo Docker ecosystem. I will obviously be contributing my changes back regardless of license permissiveness, but there's also possibly other things, both proprietary and open source, that I cannot put on the relicensing table.

Take a look at most of the Python libraries you use, Python, Docker, Linux, Git, Ruby, Django, Rails, etc. Most everything meeting the definition of a system or library will be licensed under MIT, BSD, or possibly Apache. 

This is a pretty good visualization that we keep in our wiki:

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/7397578/21956874/cd2b2702-da3e-11e6-9ee8-84cd43256c4e.png)

**Comment by pedrobaeza** [comment]
I don't have a strong opinion about this. Let's see what @Yajo thinks that is the author of the work.

**Comment by Yajo** [comment]
Docker is Apache 2.0, [and the FSF recommends that one when you need a permissive license](https://www.gnu.org/licenses/license-recommendations.html#software). You can't combine with GPL<3, but I see that as a feature too, so I'll use that one 😉 

[With it](http://choosealicense.com/licenses/apache-2.0/):

> Contributors provide an express grant of patent rights. Licensed works, modifications, and larger works may be distributed under different terms and without source code. 

Seems good enough.

I'll use [CC0](https://www.gnu.org/licenses/license-list.html#CC0) for the scaffolding branch instead.

**Comment by lasley** [comment]
Perfect, this is exactly what I needed. Thanks @Yajo.

**Comment by yelizariev** [comment]
A question about Apache license.
If I have a tool, that uses Doodba, can I use name Doodba in a slogan that describes it? Something like "Doodba-based CI tool" ?

**Comment by Yajo** [comment]
I don't have a problem on that. What do you think @pedrobaeza?

**Comment by pedrobaeza** [comment]
Not a problem on my side. The question is if the chosen license forbids it (it was not our intention). I don't think so. Any way, if you are indeed doing a CI tool, do you know https://github.com/Tecnativa/doodba-qa/?

**Comment by yelizariev** [comment]
Thanks for the answers.

About the tool. Doodba-qa is a QA tool for doodba-based projects, while I'm working on a QA tool based on doodba :smile: . It's basically a replacement for MQT with GitHub actions instead of Travis.

**Comment by pedrobaeza** [comment]
Oh, that can be great and maybe we can replace MQT in OCA by this! Let us know.

**Comment by Yajo** [comment]
If you ever get to propose replacing MQT for a doodba-based tool...

![](https://media.giphy.com/media/StpKzqTbxLGfZt6jhe/giphy.gif)

:grin: :smile: 

Although it'd be awesome.
