### ISSUE TITLE
Installing NPM Packages

### ISSUE THREAD

**Issue by felixvillafranca** [Tecnativa/docker-odoo-base#53]
Hello;

I'm not able to install 'quagga' from 'npm.
In '/opt/odoo/custom/dependencies/', following 'pip.txt' way; I add a line with 'quagga' to 'npm.txt' file.
Unfortunately, 'quagga' is not installed.

I attache image with 'log'.

<img width="516" alt="log" src="https://user-images.githubusercontent.com/4075475/28424801-dae30978-6d6e-11e7-8345-b3f39193171c.png">

Regards;

**Comment by felixvillafranca** [comment]
Great work ¡¡¡ 
Thanks,

**Comment by Yajo** [comment]
Thank you for reporting 😉
