### ISSUE TITLE
Restore tests

### ISSUE THREAD

**Issue by Yajo** [Tecnativa/docker-odoo-base#6]
This repo needs CI per pull request.

Current testing in docker hub fails for unknown reasons ([seems like the unittest script exits with a non-zero code, although tests pass](https://hub.docker.com/r/tecnativa/odoo-base/builds/b3rxqzxyeohuooe6zdve27f/)).

I removed tests in https://github.com/Tecnativa/docker-odoo-base/commit/b1308d1378c1348d120a2a7e32e58c1620256d63, I have to figure out how to apply a real CI here and how to make them work, but for now I need this image to be built.

**Comment by lasley** [comment]
Should we merge this and #14?

**Comment by Yajo** [comment]
These are issues, not PR, what do you mind by merging?

**Comment by lasley** [comment]
> what do you mind by merging?
Well there are two tickets for the same thing. Was just wondering if it made sense to leave the two open or just work under one? The management overhead of two tickets just seems meh 😉
