### ISSUE TITLE
Broken build with "text file busy"

### ISSUE THREAD

**Issue by Yajo** [Tecnativa/docker-odoo-base#65]
[Current master build is failing](https://travis-ci.org/Tecnativa/docker-odoo-base#L6771-L6783) with this log:

```
Traceback (most recent call last):
  File "/opt/odoo/common/build", line 26, in <module>
    subprocess.check_call(command)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 26] Text file busy
ERROR: Service 'odoo' failed to build: The command '/opt/odoo/common/build' returned a non-zero code: 1
```

Failure is a little bit random, but happens often. A possible workaround is to `sync` after `chmod` as explained in https://github.com/moby/moby/issues/9547#issuecomment-118682301.

**Comment by Yajo** [comment]
It was supposed to be fixed in https://github.com/Tecnativa/docker-odoo-base/commit/eecb827452e9494423ac764d2269ea057cfc9d41 and https://github.com/Tecnativa/docker-odoo-base/commit/ab0e261ec4a98c9a4c30013635f6ab966885cab4, but recent builds seem to be having the same problem again, so I'm reopening.

**Comment by lasley** [comment]
Would it be stupid to try something simple like a `sleep 10`?

**Comment by Yajo** [comment]
Maybe that would work... stupid solutions for stupid problems 😆 

I'm seeing another workaround in https://github.com/moby/moby/issues/9547#issuecomment-231562364, maybe I'll try that before.
