### ISSUE TITLE
add db-filter as parameter to odoo initialization

### ISSUE THREAD

**Issue by patovala** [Tecnativa/docker-odoo-base#83]
Hi, I need to add the db-filter option to command line execution, what would be the best way to do it? I've added a db_filter="^%d$" in custom/conf.d/10-multidb.conf and it is creating the expected key value in the auto conf but seems like I need to add the --db-filter option in the startup parameter also.

**Comment by lasley** [comment]
Take a look at [this](https://github.com/LasLabs/docker-odoo-base/blob/1be3608c2ae8fa02472f40cb2632382076b2710b/conf.d/70-security.conf) from #62
