### ISSUE TITLE
Use --internal with sane defaults in scaffoldings

### ISSUE THREAD

**Issue by Yajo** [Tecnativa/docker-odoo-base#98]
It's interesting that in the scaffolding there has been the `fakeinbox` and `fakesmtp` containers made to isolate restored backups in devel/test environments from making requests to the outside world, specifically when attempting to contact servers.

However, it turns out that since Docker 1.10, we can create networks with the `--internal` flag, which restricts access to the outside world perfectly fine (see https://github.com/moby/moby/pull/19276).

We can use that instead of using some of the proxies. It should be easier to understand for newcomers, and easier to maintain for oldcomers.

**Comment by pedrobaeza** [comment]
IMO we should replace fakesmtp for providing a mail catcher like odoo.sh does.

**Comment by Yajo** [comment]
Yes, also. I'll open a new issue for that.
